__url__ = 'https://github.com/silnrsi/pysilfont'
__copyright__ = 'Copyright (c) 2024 SIL International (https://www.sil.org)'
__license__ = 'Released under the MIT License (https://opensource.org/licenses/MIT)'
__author__ = 'David Raymond'
"""
SIL fontbakery profile for version 0.12.X
"""
# pylint: disable=line-too-long  # This is data, not code
PROFILE = {
    "check_definitions": ["silfont.fbtests.checks"],
    "sections": {
        "SIL Checks": [
            "org.sil.software/check/name/version_format",
            "org.sil.software/check/number_widths",
            "org.sil.software/check/whitespace_widths",
            "org.sil.software/check/FONTLOG",
            "org.sil.software/check/is_OFL_FAQ_present_and_current",
            "org.sil.software/check/repo/is_OFL_URL_current",
            "org.sil.software/check/repo/executable_bits"
        ],
        "Google Fonts": [
            "com.adobe.fonts/check/family/bold_italic_unique_for_nameid1",
            "com.adobe.fonts/check/family/consistent_family_name",
            "com.adobe.fonts/check/family/consistent_upm",
            "com.adobe.fonts/check/family/max_4_fonts_per_family_name",
            "com.adobe.fonts/check/fsselection_matches_macstyle",
            "com.adobe.fonts/check/name/empty_records",
            "com.adobe.fonts/check/find_empty_letters",
            "com.adobe.fonts/check/name/postscript_name_consistency",
            "com.adobe.fonts/check/nameid_1_win_english",
            "com.adobe.fonts/check/postscript_name",
            "com.adobe.fonts/check/sfnt_version",
            "com.google.fonts/check/aat",
            "com.google.fonts/check/alt_caron",
            "com.google.fonts/check/arabic_high_hamza",
            "com.google.fonts/check/arabic_spacing_symbols",
            "com.google.fonts/check/canonical_filename",
            "com.google.fonts/check/caret_slope",
            "com.google.fonts/check/case_mapping",
            "com.google.fonts/check/cmap/unexpected_subtables",
            "com.google.fonts/check/code_pages",
            "com.google.fonts/check/dotted_circle",
            "com.google.fonts/check/family_naming_recommendations",
            "com.google.fonts/check/family/control_chars",
            "com.google.fonts/check/family/equal_codepoint_coverage",
            "com.google.fonts/check/family/equal_font_versions",
            "com.google.fonts/check/family/italics_have_roman_counterparts",
            "com.google.fonts/check/family/panose_familytype",
            "com.google.fonts/check/family/single_directory",
            "com.google.fonts/check/family/tnum_horizontal_metrics",
            "com.google.fonts/check/family/underline_thickness",
            "com.google.fonts/check/family/vertical_metrics",
            "com.google.fonts/check/family/win_ascent_and_descent",
            "com.google.fonts/check/file_size",
            "com.google.fonts/check/font_names",
            "com.google.fonts/check/font_version",
            "com.google.fonts/check/fsselection",
            "com.google.fonts/check/fstype",
            "com.google.fonts/check/gdef_mark_chars",
            "com.google.fonts/check/gdef_non_mark_chars",
            "com.google.fonts/check/gdef_spacing_marks",
            "com.google.fonts/check/glyf_nested_components",
            "com.google.fonts/check/glyf_non_transformed_duplicate_components",
            "com.google.fonts/check/glyf_unused_data",
            "com.google.fonts/check/gpos_kerning_info",
            "com.google.fonts/check/gpos7",
            "com.google.fonts/check/hinting_impact",
            "com.google.fonts/check/integer_ppem_if_hinted",
            "com.google.fonts/check/italic_angle",
            "com.google.fonts/check/kern_table",
            "com.google.fonts/check/layout_valid_feature_tags",
            "com.google.fonts/check/layout_valid_language_tags",
            "com.google.fonts/check/layout_valid_script_tags",
            "com.google.fonts/check/linegaps",
            "com.google.fonts/check/loca/maxp_num_glyphs",
            "com.google.fonts/check/mac_style",
            "com.google.fonts/check/mandatory_glyphs",
            "com.google.fonts/check/maxadvancewidth",
            "com.google.fonts/check/missing_small_caps_glyphs",
            "com.google.fonts/check/monospace",
            "com.google.fonts/check/name/ascii_only_entries",
            "com.google.fonts/check/name/description_max_length",
            "com.google.fonts/check/name/family_and_style_max_length",
            "com.google.fonts/check/name/family_name_compliance",
            "com.google.fonts/check/name/familyname_first_char",
            "com.google.fonts/check/name/mandatory_entries",
            "com.google.fonts/check/name/match_familyname_fullfont",
            "com.google.fonts/check/name/no_copyright_on_description",
            "com.google.fonts/check/name/unwanted_chars",
            "com.google.fonts/check/no_debugging_tables",
            "com.google.fonts/check/os2_metrics_match_hhea",
            "com.google.fonts/check/os2/use_typo_metrics",
            "com.google.fonts/check/ots",
            "com.google.fonts/check/post_table_version",
            "com.google.fonts/check/render_own_name",
            "com.google.fonts/check/required_tables",
            "com.google.fonts/check/STAT_in_statics",
            "com.google.fonts/check/stylisticset_description",
            "com.google.fonts/check/tabular_kerning",
            "com.google.fonts/check/transformed_components",
            "com.google.fonts/check/ttx_roundtrip",
            "com.google.fonts/check/unicode_range_bits",
            "com.google.fonts/check/unique_glyphnames",
            "com.google.fonts/check/unitsperem",
            "com.google.fonts/check/unreachable_glyphs",
            "com.google.fonts/check/unwanted_tables",
            "com.google.fonts/check/usweightclass",
            "com.google.fonts/check/valid_glyphnames",
            "com.google.fonts/check/varfont/family_axis_ranges",
            "com.google.fonts/check/vendor_id",
            "com.google.fonts/check/vttclean",
            "com.google.fonts/check/whitespace_glyphnames",
            "com.google.fonts/check/whitespace_glyphs",
            "com.google.fonts/check/whitespace_ink",
            "com.google.fonts/check/whitespace_widths"
        ],
        "New checks from 0.12.10/Aug 2024": [
            "com.google.fonts/check/dsig",
            "com.google.fonts/check/family_naming_recommendations",
            "com.thetypefounders/check/features_default_languagesystem",
            "com.google.fonts/check/xavgcharwidth",
            "com.google.fonts/check/fontvalidator",
            "com.arrowtype.fonts/check/typoascender_exceeds_Agrave",
            "com.google.fonts/check/designspace_has_consistent_codepoints",
            "com.google.fonts/check/designspace_has_consistent_glyphset",
            "com.google.fonts/check/designspace_has_default_master",
            "com.google.fonts/check/designspace_has_sources",
            "com.google.fonts/check/gsub/smallcaps_before_ligatures",
            "com.google.fonts/check/name/mandatory_entries",
            "com.google.fonts/check/os2_metrics_match_hhea",
            "com.google.fonts/check/production_glyphs_similarity",
            "com.google.fonts/check/vertical_metrics_regressions",
            "com.adobe.fonts/check/find_empty_letters",
            "com.adobe.fonts/check/nameid_1_win_english",
            "com.fontwerk/check/no_mac_entries",
            "com.fontwerk/check/style_linking",
            "com.google.fonts/check/name/italic_names",
            "com.google.fonts/check/cmap/unexpected_subtables",
            "com.google.fonts/check/iso15008_intercharacter_spacing",
            "com.google.fonts/check/iso15008_interline_spacing",
            "com.google.fonts/check/iso15008_interword_spacing",
            "com.google.fonts/check/iso15008_proportions",
            "com.google.fonts/check/iso15008_proportions",
            "com.google.fonts/check/iso15008_stem_width",
            "com.google.fonts/check/unicode_range_bits",
            "com.google.fonts/check/rupee",
            "com.microsoft/check/manufacturer",
            "com.microsoft/check/name_id_1",
            "com.microsoft/check/name_id_2",
            "com.microsoft/check/name_length_req",
            "com.microsoft/check/office_ribz_req",
            "com.microsoft/check/tnum_glyphs_equal_widths",
            "com.microsoft/check/trademark",
            "com.microsoft/check/typographic_family_name",
            "com.microsoft/check/version",
            "com.microsoft/check/vtt_volt_data",
            "com.typenetwork/check/PUA_encoded_glyphs",
            "com.typenetwork/check/composite_glyphs",
            "com.typenetwork/check/family/duplicated_names",
            "com.typenetwork/check/family/tnum_horizontal_metrics",
            "com.typenetwork/check/family/valid_strikeout",
            "com.typenetwork/check/family/valid_underline",
            "com.typenetwork/check/font_is_centered_vertically",
            "com.typenetwork/check/glyph_coverage",
            "com.typenetwork/check/marks_width",
            "com.typenetwork/check/name/mandatory_entries"
            ],
    },
    "overrides": {
        "com.google.fonts/check/alt_caron": [
            {
                "code": "decomposed-outline",
                "status": "PASS",
                "reason": "some SIL fonts intentionally use decomposed outlines for Lcaron, dcaron, lcaron and tcaron."
            }
            ],
        "com.google.fonts/check/legacy_accents": [
            {
                "code": "legacy-accent-components",
                "status": "PASS",
                "reason": "SIL disagrees with the premise of this check."
            }
        ],
        "com.google.fonts/check/whitespace_glyphs": [
            {
                "code": "missing-whitespace-glyph-0x00A0",
                "status": "WARN",
                "reason": "this is not as severe as assessed in the original check for 0x00A0.",
            }
        ],
    },
    "configuration_defaults": {
        "com.google.fonts/check/file_size": {
            "WARN_SIZE": 1 * 1024 * 1024,
            "FAIL_SIZE": 9 * 1024 * 1024,
        }
    },
}
