#!/bin/sh
if [ $# -eq 0 ]
then
  echo "No font name"
  exit
fi

BASE=~/testdata/norm/$1.ufo
SUBDIR=~/testdata/norm/$1_tests
PREF=${SUBDIR}/$1

if [ -d $BASE ]
then
	if [ -d $SUBDIR ] ; then rm -r $SUBDIR ; fi
	mkdir $SUBDIR

	python ~/src/pysilfont/scripts/samples/UFOnormdemo.py 	$BASE  			${PREF}_norm.ufo

	python ~/src/pysilfont/scripts/samples/rtripFF.py 	$BASE  			${PREF}_FF.ufo
	python ~/src/pysilfont/scripts/samples/rtripFF.py 	${PREF}_norm.ufo	${PREF}_norm_FF.ufo

	python ~/src/pysilfont/scripts/samples/UFOnormdemo.py 	${PREF}_norm_FF.ufo	${PREF}_norm_FF_norm.ufo
	python ~/src/pysilfont/scripts/samples/UFOnormdemo.py 	${PREF}_FF.ufo		${PREF}_FF_norm.ufo

else
	echo "ufo does not exist"
fi
 

