#!/bin/sh
# Sample script for calling multiple routines on a project, typically prior to committing to a repository.
# Place this in root of a project, adjust the font path, then set it to be executable by typing:
# chmod +x preflight

psfnormalize -p checkfix=fix source/font-Regular.ufo
psfnormalize -p checkfix=fix source/font-Bold.ufo

psfsyncmasters source/font-RB.designspace
