#!/usr/bin/env python
'''Convert/normalise a UFO.
- If no options are chosen, the output font will simply be a normalised version of the font.'''
__url__ = 'http://github.com/silnrsi/pysilfont'
__copyright__ = 'Copyright (c) 2015, SIL International  (http://www.sil.org)'
__license__ = 'Released under the MIT License (http://opensource.org/licenses/MIT)'
__author__ = 'David Raymond'
__version__ = '1.0.0'

from silfont.genlib import *
from silfont.UFOlib import *

argspec = [
    ('ifont',{'help': 'Input font file'}, {'type': 'infont'}),
    ('ofont',{'help': 'Output font file','nargs': '?' }, {'type': 'outfont', 'def': '_conv'}),
    ('-l','--log',{'help': 'Log file'}, {'type': 'outfile', 'def': '_UFOconvert.log'}),
    ('-v','--version',{'help': 'UFO version to output'},{}),
    ('-p','--params',{'help': 'Other font parameters - see user docs','action': 'append'}, {'type': 'optiondict'})]

def doit(args) :
    font = args.ifont
    return args.ifont

execute("PSFU",doit, argspec)