#!/usr/bin/python

from silfont.makegdl.font import Font
import silfont.makegdl.ot
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('infont')
parser.add_argument('outgdl')
parser.add_argument('-a','--ap')
parser.add_argument('-i','--include')
parser.add_argument('-y','--alias')
args = parser.parse_args()

f = Font(args.infont)
if args.alias : f.loadAlias(args.alias)
if args.ap : f.loadAP(args.ap)

f.createClasses()
f.calculateOTLookups()
f.calculatePointClasses()
f.ligClasses()

outf = open(args.outgdl, "w")
f.outGDL(outf, args)
outf.close()

